import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// Importing Components
import Hero from "../components/Hero";

export default function Home() {

  const sectionOne = <Hero heroImage={'image_home'} />

  const sectionTwo = (
    <section>
      <h2>EXPERIENCE MATTERS.</h2>
      <span>
        We're a small, local company specializing in home repairs,
        kitchen & bath remodels, garage conversions and much more.
        25 years experience. No job too big or too small.
      </span>
    </section>
  )
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {sectionOne}
        {sectionTwo}
      </main>
    </>
  )
}
